version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: rpallas/prometheus:latest@sha256:771e0aad94372291e959b1ef4e6ea5434f5155e287cd56d5bc83ccbeea9e5e4e
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest@sha256:d134958cb61e30b1bc155b7978ec022f7701a80bdae83ab0b6c45ea7258f76a5
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  grafana_init:
    entrypoint: "/opt/init.sh"
    depends_on:
      - grafana
    image: grafana/grafana:latest@sha256:d134958cb61e30b1bc155b7978ec022f7701a80bdae83ab0b6c45ea7258f76a5
    volumes:
      - ./init.sh:/opt/init.sh
  crypto-exporter:
    environment:
      - CRYPTO_EXPORTER_ADDRESS=${CRYPTO_EXPORTER_ADDRESS}
    image: rpallas/crypto-exporter:latest@sha256:a758e96d6b9906bd94de51658f65845d33852e6a42d0731c4fbfc4a96ee0f241
    # build: ../

