version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: rpallas/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  grafana_init:
    entrypoint: "/opt/init.sh"
    depends_on:
      - grafana
    image: grafana/grafana:latest
    volumes:
      - ./init.sh:/opt/init.sh
  crypto-exporter:
    environment:
      - CRYPTO_EXPORTER_ADDRESS=${CRYPTO_EXPORTER_ADDRESS}
    image: rpallas/crypto-exporter:latest
    # build: ../

